### ISSUE TITLE
[Request]: How to set the level of sweep search parameters?

### ISSUE THREAD

**Issue by ylhz** [wandb/examples#140]
### What is about?

How do I proceed if I search for parameters that have subparameters to search for? 
For example, SGD has the parameter momentum and Adam does not have that parameter. If I directly set it up like below, then it may produce duplicate experiments, or meaningless experiments.
```yaml
parameters:
  optimizer: 
    values: ['sgd','adam']
  momentum:
    values:[0.8, 0.9, 0.95]
```
Suppose that two sets of parameters A, B are searched.
A: optimizer: 'adam', momentum: 0.8
B: optimizer: 'adam', momentum: 0.9
But the final searched parameter combinations A and B are actually the same experiment.
