### ISSUE TITLE
[Request]:  Full run of the sweep function in pytorch using yaml files

### ISSUE THREAD

**Issue by vinith2** [wandb/examples#170]
### What is about?

I am trying to use sweep in pytorch with parameters for the sweep stored in a yaml file. There are no examples with full run of the code, all are in bits and pieces.

**Comment by scottire** [comment]
Thanks for flagging this. There's an example that uses a YAML file and PyTorch under the `examples/pytorch` directory: [pytorch-cnn-fashion](https://github.com/wandb/examples/tree/master/examples/pytorch/pytorch-cnn-fashion). 

This example of using Sweeps with PyTorch might be useful to you if you want an overview of Sweeps alongside Python, although it uses a python dictionary rather than a YAML file: [https://github.com/wandb/examples/blob/master/colabs/pytorch/Organizing_Hyperparameter_Sweeps_in_PyTorch_with_W%26B.ipynb](https://github.com/wandb/examples/blob/master/colabs/pytorch/Organizing_Hyperparameter_Sweeps_in_PyTorch_with_W%26B.ipynb)
Here's some documentation on using YAML files: 
[https://docs.wandb.ai/guides/sweeps/quickstart](https://docs.wandb.ai/guides/sweeps/quickstart)

Here is the dictionary in Sweeps with PyTorch Notebook example converted to a YAML file: 
```yaml
program: train.py
method: bayes
metric:
  name: loss
  goal: minimize
parameters:
  learning_rate:
    distribution: uniform
    min: 0.0001
    max: 0.1
  batch_size:
    distribution: q_log_uniform
    min: 1.5
    max: 2.5
  optimizer:
    values: ["adam", "sgd"]
  epoch:
    value: 1
```
