### ISSUE TITLE
How to run sweep with a train.py code that receives a YAML file as argument

### ISSUE THREAD

**Issue by imayachita** [wandb/examples#62]
Hello!
I've been trying to use sweep in my project where the `train.py` accepts a YAML file as argument, where all the hyperparameters are defined. This is an example how I run my `train.py` file:
`python3 train.py config_yaml.yaml`

How can I configure my sweep configuration this way? If for example I have `sweep_config.yaml` that contains:
```
program: train.py
method: grid
parameters:
  hidden_layers:
    values: [1024, 2048]
  optimizer:
    values: ["adam", "sgd"]
```

I can't run `wandb sweep sweep_config.yaml` because wandb will translate this to be something like `python3 train.py --hidden_layers=1024 --optimizer="adam"`. 
Another question is that, if I define default hyperparams values in the code, can I overwrite it with the values specified in the config file?

Thank you.

**Comment by charlesfrye** [comment]
Hey there imayachita!

   There's not a really great way to combine Sweeps with a script that is itself solely configured by YAML files. The assumption of Sweeps that makes it useful is that the agents are executing Python programs that take in hyperparameters via the CLI. That way, the Sweep Controller can generate a new set of hyperparameters and send them to the agent, as command line arguments, for execution.
     
   It seems like you might be intending to set some parameters via the Sweep Controller (above, `hidden_layers` and `optimizer`) and set others via the `config.yaml` (maybe learning rate, filepaths, etc.). If that's the case, you can pass the `config.yaml` to all of the runs using the [`command` parameter](https://docs.wandb.ai/sweeps/configuration#command). The final command that gets sent to an agent by the Controller then looks something like `python3 train.py config_yaml.yaml --hidden_layers=1024 --optimizer="adam"`.

**Comment by imayachita** [comment]
Thank you! How can we set how many trials we want to run?

**Comment by imayachita** [comment]
I also faced an error when trying to add `metric` parameter inside the sweep yaml file.

```
program: train.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - train_config.yaml
  - ${args}
parameters:
  hidden-layers:
    values: [3,4,5]
  hidden-units:
    min: 1000
    max: 1200
    distribution: int_uniform
  learning-rate:
    min: 1e-5
    max: 1e-4
    distribution: uniform
  optimizer:
    value: "adam-v2"
```

This is the error I got:
```
wandb.errors.error.CommError: Invalid sweep config: KeyError: 'metric'

Error: Invalid sweep config: KeyError: 'metric'
```

Anyway, I don't use `wandb.log`, but I use `wandb.keras.WandbCallback` to log my metrics. Thank you!
